//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingFood
    {
        public int BookFoodID { get; set; }
        public string FoodType { get; set; }
        public string MealType { get; set; }
        public Nullable<int> DishType { get; set; }
        public Nullable<int> DishName { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int BookingID { get; set; }
    }
}
